// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthProfileByID = `-- name: GetAuthProfileByID :one
SELECT id, role
FROM profiles
WHERE id = $1
  AND deleted_at IS NULL
`

type GetAuthProfileByIDRow struct {
	ID   pgtype.UUID `json:"id"`
	Role UserRole    `json:"role"`
}

func (q *Queries) GetAuthProfileByID(ctx context.Context, id pgtype.UUID) (GetAuthProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthProfileByID, id)
	var i GetAuthProfileByIDRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const getBookingPropertyID = `-- name: GetBookingPropertyID :one
SELECT property_id
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBookingPropertyID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBookingPropertyID, id)
	var property_id pgtype.UUID
	err := row.Scan(&property_id)
	return property_id, err
}

const getHostIDForProfile = `-- name: GetHostIDForProfile :one
SELECT id
FROM hosts
WHERE profile_id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetHostIDForProfile(ctx context.Context, profileID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getHostIDForProfile, profileID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const isHostOfProperty = `-- name: IsHostOfProperty :one
SELECT EXISTS (
  SELECT 1
  FROM properties p
  INNER JOIN hosts h ON h.id = p.host_id
  WHERE p.id = $1
    AND p.deleted_at IS NULL
    AND h.profile_id = $2
    AND h.deleted_at IS NULL
)::boolean AS is_host
`

type IsHostOfPropertyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProfileID pgtype.UUID `json:"profile_id"`
}

func (q *Queries) IsHostOfProperty(ctx context.Context, arg IsHostOfPropertyParams) (bool, error) {
	row := q.db.QueryRow(ctx, isHostOfProperty, arg.ID, arg.ProfileID)
	var is_host bool
	err := row.Scan(&is_host)
	return is_host, err
}

const profileIsAdmin = `-- name: ProfileIsAdmin :one
SELECT EXISTS (
  SELECT 1
  FROM profiles
  WHERE id = $1
    AND role = 'admin'::user_role
    AND deleted_at IS NULL
)::boolean AS is_admin
`

func (q *Queries) ProfileIsAdmin(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, profileIsAdmin, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}
