// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccommodationType string

const (
	AccommodationTypeShareHouse   AccommodationType = "share-house"
	AccommodationTypeStudio       AccommodationType = "studio"
	AccommodationTypeMicroStudio  AccommodationType = "micro-studio"
	AccommodationTypeMultiBedroom AccommodationType = "multi-bedroom"
)

func (e *AccommodationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccommodationType(s)
	case string:
		*e = AccommodationType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccommodationType: %T", src)
	}
	return nil
}

type NullAccommodationType struct {
	AccommodationType AccommodationType `json:"accommodation_type"`
	Valid             bool              `json:"valid"` // Valid is true if AccommodationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccommodationType) Scan(value interface{}) error {
	if value == nil {
		ns.AccommodationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccommodationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccommodationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccommodationType), nil
}

type BookingMode string

const (
	BookingModeInstant BookingMode = "instant"
	BookingModeRequest BookingMode = "request"
)

func (e *BookingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingMode(s)
	case string:
		*e = BookingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingMode: %T", src)
	}
	return nil
}

type NullBookingMode struct {
	BookingMode BookingMode `json:"booking_mode"`
	Valid       bool        `json:"valid"` // Valid is true if BookingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingMode) Scan(value interface{}) error {
	if value == nil {
		ns.BookingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingMode), nil
}

type BookingStatus string

const (
	BookingStatusRequested      BookingStatus = "requested"
	BookingStatusPendingPayment BookingStatus = "pending_payment"
	BookingStatusExpired        BookingStatus = "expired"
	BookingStatusConfirmed      BookingStatus = "confirmed"
	BookingStatusPaymentFailed  BookingStatus = "payment_failed"
	BookingStatusActive         BookingStatus = "active"
	BookingStatusCompleted      BookingStatus = "completed"
	BookingStatusCancelled      BookingStatus = "cancelled"
	BookingStatusRejected       BookingStatus = "rejected"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type BookingType string

const (
	BookingTypeInstant BookingType = "instant"
	BookingTypeRequest BookingType = "request"
)

func (e *BookingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingType(s)
	case string:
		*e = BookingType(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingType: %T", src)
	}
	return nil
}

type NullBookingType struct {
	BookingType BookingType `json:"booking_type"`
	Valid       bool        `json:"valid"` // Valid is true if BookingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingType) Scan(value interface{}) error {
	if value == nil {
		ns.BookingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingType), nil
}

type HostStatus string

const (
	HostStatusPending   HostStatus = "pending"
	HostStatusActive    HostStatus = "active"
	HostStatusSuspended HostStatus = "suspended"
)

func (e *HostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HostStatus(s)
	case string:
		*e = HostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HostStatus: %T", src)
	}
	return nil
}

type NullHostStatus struct {
	HostStatus HostStatus `json:"host_status"`
	Valid      bool       `json:"valid"` // Valid is true if HostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HostStatus), nil
}

type HousingRequestStatus string

const (
	HousingRequestStatusNew        HousingRequestStatus = "new"
	HousingRequestStatusInProgress HousingRequestStatus = "in_progress"
	HousingRequestStatusClosed     HousingRequestStatus = "closed"
)

func (e *HousingRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HousingRequestStatus(s)
	case string:
		*e = HousingRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HousingRequestStatus: %T", src)
	}
	return nil
}

type NullHousingRequestStatus struct {
	HousingRequestStatus HousingRequestStatus `json:"housing_request_status"`
	Valid                bool                 `json:"valid"` // Valid is true if HousingRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHousingRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HousingRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HousingRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHousingRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HousingRequestStatus), nil
}

type NotificationType string

const (
	NotificationTypeBookingRequest   NotificationType = "booking_request"
	NotificationTypeBookingConfirmed NotificationType = "booking_confirmed"
	NotificationTypeBookingRejected  NotificationType = "booking_rejected"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusConfirmed PaymentStatus = "confirmed"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusCancelled PaymentStatus = "cancelled"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PropertyEmbeddingSyncStatus string

const (
	PropertyEmbeddingSyncStatusPending       PropertyEmbeddingSyncStatus = "pending"
	PropertyEmbeddingSyncStatusSynced        PropertyEmbeddingSyncStatus = "synced"
	PropertyEmbeddingSyncStatusFailed        PropertyEmbeddingSyncStatus = "failed"
	PropertyEmbeddingSyncStatusNotApplicable PropertyEmbeddingSyncStatus = "not_applicable"
)

func (e *PropertyEmbeddingSyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropertyEmbeddingSyncStatus(s)
	case string:
		*e = PropertyEmbeddingSyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PropertyEmbeddingSyncStatus: %T", src)
	}
	return nil
}

type NullPropertyEmbeddingSyncStatus struct {
	PropertyEmbeddingSyncStatus PropertyEmbeddingSyncStatus `json:"property_embedding_sync_status"`
	Valid                       bool                        `json:"valid"` // Valid is true if PropertyEmbeddingSyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropertyEmbeddingSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PropertyEmbeddingSyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropertyEmbeddingSyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropertyEmbeddingSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropertyEmbeddingSyncStatus), nil
}

type PropertyStatus string

const (
	PropertyStatusDraft         PropertyStatus = "draft"
	PropertyStatusPendingReview PropertyStatus = "pending_review"
	PropertyStatusPublished     PropertyStatus = "published"
	PropertyStatusArchived      PropertyStatus = "archived"
)

func (e *PropertyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropertyStatus(s)
	case string:
		*e = PropertyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PropertyStatus: %T", src)
	}
	return nil
}

type NullPropertyStatus struct {
	PropertyStatus PropertyStatus `json:"property_status"`
	Valid          bool           `json:"valid"` // Valid is true if PropertyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropertyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PropertyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropertyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropertyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropertyStatus), nil
}

type RoomStatus string

const (
	RoomStatusAvailable   RoomStatus = "available"
	RoomStatusUnavailable RoomStatus = "unavailable"
	RoomStatusArchived    RoomStatus = "archived"
)

func (e *RoomStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomStatus(s)
	case string:
		*e = RoomStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomStatus: %T", src)
	}
	return nil
}

type NullRoomStatus struct {
	RoomStatus RoomStatus `json:"room_status"`
	Valid      bool       `json:"valid"` // Valid is true if RoomStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RoomStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomStatus), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleHost     UserRole = "host"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Amenity struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Icon      *string            `json:"icon"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ApiRateLimit struct {
	Bucket       string             `json:"bucket"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
	RequestCount int32              `json:"request_count"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	RoomID            pgtype.UUID        `json:"room_id"`
	PropertyID        pgtype.UUID        `json:"property_id"`
	CheckIn           pgtype.Date        `json:"check_in"`
	CheckOut          pgtype.Date        `json:"check_out"`
	GuestCount        int32              `json:"guest_count"`
	Status            BookingStatus      `json:"status"`
	BookingType       BookingType        `json:"booking_type"`
	HoldExpiresAt     pgtype.Timestamptz `json:"hold_expires_at"`
	CustomerNotes     *string            `json:"customer_notes"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy        pgtype.UUID        `json:"approved_by"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PaymentRetryCount int32              `json:"payment_retry_count"`
}

type BookingPriceSnapshot struct {
	BookingID        pgtype.UUID        `json:"booking_id"`
	RentKrw          int32              `json:"rent_krw"`
	ServiceFeeKrw    int32              `json:"service_fee_krw"`
	UtilitiesKrw     int32              `json:"utilities_krw"`
	TotalKrw         int32              `json:"total_krw"`
	PricingVersion   string             `json:"pricing_version"`
	NightlyBreakdown []byte             `json:"nightly_breakdown"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Host struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	DisplayName string             `json:"display_name"`
	Status      HostStatus         `json:"status"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type HousingRequest struct {
	ID                pgtype.UUID          `json:"id"`
	CustomerID        pgtype.UUID          `json:"customer_id"`
	Email             string               `json:"email"`
	DesiredArea       string               `json:"desired_area"`
	CheckIn           pgtype.Date          `json:"check_in"`
	CheckOut          pgtype.Date          `json:"check_out"`
	BudgetMax         *int32               `json:"budget_max"`
	AccommodationType *AccommodationType   `json:"accommodation_type"`
	Notes             *string              `json:"notes"`
	Status            HousingRequestStatus `json:"status"`
	CreatedAt         pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz   `json:"updated_at"`
}

type LocationAlias struct {
	ID           pgtype.UUID        `json:"id"`
	Alias        string             `json:"alias"`
	District     string             `json:"district"`
	CenterLat    float64            `json:"center_lat"`
	CenterLng    float64            `json:"center_lng"`
	RadiusMeters int32              `json:"radius_meters"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      NotificationType   `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Metadata  []byte             `json:"metadata"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID           pgtype.UUID        `json:"id"`
	OrderID      pgtype.UUID        `json:"order_id"`
	PaymentKey   *string            `json:"payment_key"`
	BookingID    pgtype.UUID        `json:"booking_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	AmountKrw    int32              `json:"amount_krw"`
	Status       PaymentStatus      `json:"status"`
	TossResponse []byte             `json:"toss_response"`
	FailedReason *string            `json:"failed_reason"`
	ConfirmedAt  pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PaymentEvent struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     string             `json:"event_id"`
	PaymentID   pgtype.UUID        `json:"payment_id"`
	BookingID   pgtype.UUID        `json:"booking_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type PlatformSetting struct {
	ID             int16              `json:"id"`
	ServiceFeeBps  int32              `json:"service_fee_bps"`
	HoldTtlMinutes int32              `json:"hold_ttl_minutes"`
	PricingVersion string             `json:"pricing_version"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID                pgtype.UUID        `json:"id"`
	Role              UserRole           `json:"role"`
	FullName          string             `json:"full_name"`
	Phone             *string            `json:"phone"`
	AvatarUrl         *string            `json:"avatar_url"`
	PreferredLanguage string             `json:"preferred_language"`
	MarketingConsent  bool               `json:"marketing_consent"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Property struct {
	ID                       pgtype.UUID                  `json:"id"`
	HostID                   pgtype.UUID                  `json:"host_id"`
	Title                    string                       `json:"title"`
	Slug                     string                       `json:"slug"`
	Description              string                       `json:"description"`
	PropertyType             AccommodationType            `json:"property_type"`
	AddressLine1             string                       `json:"address_line1"`
	AddressLine2             *string                      `json:"address_line2"`
	City                     string                       `json:"city"`
	PostalCode               *string                      `json:"postal_code"`
	Country                  string                       `json:"country"`
	Location                 []byte                       `json:"location"`
	District                 string                       `json:"district"`
	NearestStationName       *string                      `json:"nearest_station_name"`
	NearestStationWalkMin    *int32                       `json:"nearest_station_walk_min"`
	Status                   PropertyStatus               `json:"status"`
	BookingMode              BookingMode                  `json:"booking_mode"`
	MinStayNights            int32                        `json:"min_stay_nights"`
	MonthlyPriceMin          *int32                       `json:"monthly_price_min"`
	IsFeatured               bool                         `json:"is_featured"`
	Tags                     []string                     `json:"tags"`
	PublishedAt              pgtype.Timestamptz           `json:"published_at"`
	DeletedAt                pgtype.Timestamptz           `json:"deleted_at"`
	CreatedAt                pgtype.Timestamptz           `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz           `json:"updated_at"`
	EmbeddingSyncStatus      *PropertyEmbeddingSyncStatus `json:"embedding_sync_status"`
	EmbeddingSyncRequestedAt pgtype.Timestamptz           `json:"embedding_sync_requested_at"`
	EmbeddingSyncedAt        pgtype.Timestamptz           `json:"embedding_synced_at"`
	EmbeddingSyncError       *string                      `json:"embedding_sync_error"`
	EmbeddingSyncAttempts    int32                        `json:"embedding_sync_attempts"`
}

type PropertyAmenity struct {
	PropertyID pgtype.UUID `json:"property_id"`
	AmenityID  pgtype.UUID `json:"amenity_id"`
}

type PropertyImage struct {
	ID          pgtype.UUID        `json:"id"`
	PropertyID  pgtype.UUID        `json:"property_id"`
	StoragePath string             `json:"storage_path"`
	SortOrder   int32              `json:"sort_order"`
	AltText     *string            `json:"alt_text"`
	IsCover     bool               `json:"is_cover"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PropertySearchEmbedding struct {
	PropertyID  pgtype.UUID        `json:"property_id"`
	Content     string             `json:"content"`
	ContentHash string             `json:"content_hash"`
	Embedding   []byte             `json:"embedding"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID              pgtype.UUID        `json:"id"`
	PropertyID      pgtype.UUID        `json:"property_id"`
	Name            string             `json:"name"`
	RoomType        *string            `json:"room_type"`
	SizeSqm         pgtype.Numeric     `json:"size_sqm"`
	MaxOccupancy    int32              `json:"max_occupancy"`
	MonthlyPriceKrw int32              `json:"monthly_price_krw"`
	Status          RoomStatus         `json:"status"`
	AvailableFrom   pgtype.Date        `json:"available_from"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RoomImage struct {
	ID          pgtype.UUID        `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	StoragePath string             `json:"storage_path"`
	SortOrder   int32              `json:"sort_order"`
	AltText     *string            `json:"alt_text"`
	IsCover     bool               `json:"is_cover"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
